import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import { useState } from "react";
import { Trash2, RefreshCw, ChevronDown, ChevronUp } from "lucide-react";
export function WebsiteItem({ website, changes, onCrawl, onDelete, crawling = false, deleting = false, }) {
    const [expanded, setExpanded] = useState(false);
    const lastChange = changes[0];
    return (_jsxs("div", { className: "bg-white border border-gray-200 rounded-lg shadow-sm hover:shadow-md transition", children: [_jsxs("div", { className: "p-4", children: [_jsxs("div", { className: "flex items-start justify-between mb-2", children: [_jsxs("div", { className: "flex-1", children: [_jsx("h3", { className: "text-lg font-semibold text-gray-900", children: website.name }), _jsx("p", { className: "text-sm text-gray-500 truncate", children: website.url }), _jsxs("p", { className: "text-xs text-gray-400 mt-1", children: ["Hinzugef\u00FCgt am", " ", new Date(website.createdAt).toLocaleDateString("de-DE")] })] }), _jsxs("div", { className: "flex gap-2", children: [_jsx("button", { onClick: () => onCrawl(website.id), disabled: crawling || deleting, title: "Starte Crawl", className: "p-2 text-blue-600 hover:bg-blue-50 rounded disabled:opacity-50 disabled:cursor-not-allowed", children: _jsx(RefreshCw, { size: 18, className: crawling ? "animate-spin" : "" }) }), _jsx("button", { onClick: () => onDelete(website.id), disabled: deleting || crawling, title: "Website l\u00F6schen", className: "p-2 text-red-600 hover:bg-red-50 rounded disabled:opacity-50 disabled:cursor-not-allowed", children: _jsx(Trash2, { size: 18 }) })] })] }), lastChange && (_jsxs("div", { className: "mt-3 pt-3 border-t border-gray-100", children: [_jsxs("p", { className: "text-sm text-gray-600", children: [_jsx("span", { className: "font-medium", children: "Letzte \u00DCberpr\u00FCfung:" }), " ", new Date(lastChange.data?.timestamp).toLocaleString("de-DE")] }), _jsxs("p", { className: "text-sm text-gray-600 mt-1", children: [_jsx("span", { className: "font-medium", children: "Status:" }), " ", _jsx("span", { className: lastChange.data?.similarity ?? 1 > 0.95
                                            ? "text-green-600"
                                            : "text-orange-600", children: lastChange.data?.similarity
                                            ? `${(lastChange.data.similarity * 100).toFixed(0)}% ähnlich`
                                            : "Änderungen erkannt" })] })] })), changes.length > 0 && (_jsxs("button", { onClick: () => setExpanded(!expanded), className: "mt-3 w-full flex items-center justify-between p-2 text-sm text-gray-600 hover:bg-gray-50 rounded", children: [_jsxs("span", { children: ["Verlauf anzeigen (", changes.length, ")"] }), expanded ? _jsx(ChevronUp, { size: 16 }) : _jsx(ChevronDown, { size: 16 })] }))] }), expanded && changes.length > 0 && (_jsx("div", { className: "border-t border-gray-200 bg-gray-50 p-4", children: _jsx("div", { className: "space-y-3 max-h-96 overflow-y-auto", children: changes.map((change) => (_jsxs("div", { className: "bg-white p-3 rounded border border-gray-200 text-sm", children: [_jsx("p", { className: "text-gray-500 mb-2", children: new Date(change.data?.timestamp).toLocaleString("de-DE") }), _jsx("p", { className: "text-gray-700 whitespace-pre-wrap max-h-48 overflow-y-auto", children: change.data?.changes ||
                                    "Keine Änderungsbeschreibung verfügbar" })] }, change.id))) }) }))] }));
}
